services:
  api-portal:
    ports:
      - "8458:8000"

  dashboard-api:
    container_name: ts-arena-dashboard-api
    ports:
      - "8485:8000"

  cloudbeaver:
    container_name: cloudbeaver
    ports:
      - "8979:8978"

volumes:
  dbarena:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volume-nbg1-1/storage/ts-arena-db
