schedules:
- id: smard_dam_challenge_24h_15min
  cron: 0 14 * * *
  run_on_startup: false
  params:
    description: 'Day-Ahead Market Price Challenge: 24h horizon, 15-min frequency'
    domains:
    - energy
    subdomains:
    - price
    required_time_series:
    - series_unique_id1
    - series_unique_id2
    - series_unique_id3
    # ...
    n_time_series: 15
    frequency: 15 minutes
    context_length: 1000
    forecast_horizon: 1 day
    announce_lead: 1 day 10 hours
    registration_duration: 1 hour
    evaluation_delay: 0 hours
- id: smard_load_challenge_24h_15min
  cron: 0 7 * * *
  run_on_startup: false
  params:
    description: 'Net Load Challenge: 24h horizon, 15-min frequency'
    domains:
    - energy
    subdomains:
    - consumption
    required_time_series:
    - series_unique_id1
    - series_unique_id2
    - series_unique_id3
    # ...
    n_time_series: 10
    frequency: 15 minutes
    context_length: 1000
    forecast_horizon: 1 day
    announce_lead: 15 minutes
    registration_duration: 15 minutes
    evaluation_delay: 0 hours
- id: smard_generation_challenge_24h_15min
  cron: 0 19 * * *
  run_on_startup: false
  params:
    description: 'Generation Challenge: All generation types, 24h horizon, 15-min
      frequency'
    domains:
    - energy
    subdomains:
    - generation
    required_time_series:
    - series_unique_id1
    - series_unique_id2
    - series_unique_id3
    # ...
    n_time_series: 28
    frequency: 15 minutes
    context_length: 1000
    forecast_horizon: 1 day
    announce_lead: 15 minutes
    registration_duration: 15 minutes
    evaluation_delay: 0 hours
- id: smard_dam_challenge_72h_1h
  cron: 0 14 * * *
  run_on_startup: false
  params:
    description: 'Day-Ahead Market Price Challenge: 72h horizon, 1h frequency'
    domains:
    - energy
    subdomains:
    - price
    required_time_series:
    - series_unique_id1
    - series_unique_id2
    - series_unique_id3
    # ...
    n_time_series: 15
    frequency: 1 hour
    context_length: 1000
    forecast_horizon: 3 days
    announce_lead: 1 day 10 hours
    registration_duration: 1 hour
    evaluation_delay: 0 hours
- id: smard_load_challenge_72h_1h
  cron: 0 8 * * *
  run_on_startup: false
  params:
    description: 'Net Load Challenge: 72h horizon, 1h frequency'
    domains:
    - energy
    subdomains:
    - consumption
    required_time_series:
    - series_unique_id1
    - series_unique_id2
    - series_unique_id3
    # ...
    n_time_series: 10
    frequency: 1 hour
    context_length: 1000
    forecast_horizon: 3 days
    announce_lead: 1 hour
    registration_duration: 1 hour
    evaluation_delay: 0 hours
- id: smard_generation_challenge_72h_1h
  cron: 0 20 * * *
  run_on_startup: false
  params:
    description: 'Generation Challenge: All generation types, 72h horizon, 1h frequency'
    domains:
    - energy
    subdomains:
    - generation
    required_time_series:
    - series_unique_id1
    - series_unique_id2
    - series_unique_id3
    # ...
    n_time_series: 56
    frequency: 1 hour
    context_length: 1000
    forecast_horizon: 3 days
    announce_lead: 1 hour
    registration_duration: 1 hour
    evaluation_delay: 0 hours
